### ISSUE TITLE
how to know a successful bind

### ISSUE THREAD

**Issue by gentunian** [Alaneor/AD-X#9]
`bind()` function ignores completely `ldap_bind()` return value. There's no way to check wether or not the bind was successful. Also, it's not recommended by the author to use the resource from `get_link()`, and that would be, from an OOP perspective correct.

How to check for successful bind? i.e. how to know if ldap_bind() returned FALSE somehow, as `isBound` is never used.

**Comment by gentunian** [comment]
must say without catching exceptions.

**Comment by Alaneor** [comment]
The `bind()` method returns the current instance on success - this is by design. If there's an unsuccessful bind, then an exception is raised - see [this code](https://github.com/Alaneor/AD-X/blob/master/ADX/Core/Link.php#L380) for details about what exception is raised when.

You can always only `catch (\Exception $e) {}` if you only care about success/failure and do not need to know the exact reason.

**Comment by gentunian** [comment]
I saw the code before creating the issue, that's why I saw the protected attribute `isBound` that is not being used. Finally I added the comment about exceptions.

Another perspective would be:

    $link = new Link('mydomain.com');
    $link->bind('user@mydomain.com', 'password');
    if ($link->isBound()) {
        // ...
    }

**Comment by Alaneor** [comment]
Ah, I see. It seems, though, that the `$isBound` attribute is not used at all - I might have added it to the class in the beginning but decided that there is no use case for it, most likely because I throw an exception on unsuccessful bind.

The code you propose would also only work as long as the `bind()` method would not throw an exception. And I would not like to go that way...

**Comment by gentunian** [comment]
Got it then, will catch exception. Making a second thought, exception would clarify error messages.
